# Generated by Django 5.2 on 2025-04-25 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_category_options_video_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
    ]
