# Generated by Django 5.2 on 2025-04-25 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_remove_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='date_passed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
