# Generated by Django 5.2 on 2025-04-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_module_date_passed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='file',
        ),
    ]
