# Generated by Django 5.2 on 2025-04-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_rename_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
