# Generated by Django 5.2 on 2025-04-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('ready', 'Ready')], default='uploading', max_length=20),
        ),
    ]
