# Generated by Django 5.2 on 2025-04-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_video_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('ready', 'Ready')], default='uploading', max_length=10),
        ),
    ]
