# Generated by Django 5.2 on 2025-05-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0008_alter_video_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="status",
            field=models.CharField(
                choices=[("uploading", "Uploading"), ("ready", "Ready")],
                default="uploading",
                editable=False,
                max_length=10,
            ),
        ),
    ]
