# Generated by Django 5.2 on 2025-05-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0009_alter_video_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not started", "Not Started"),
                    ("Active", "Active"),
                    ("Finished", "Finished"),
                ],
                default="Not started",
            ),
        ),
    ]
